services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyAMC0:/dev/ttyAMC0
    restart: unless-stopped
    network_mode: host
    privileged: true
