services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./home-assistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model small-int8
    ports:
      - "10300:10300"
    restart: unless-stopped

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice en_US-lessac-medium
    ports:
      - "10200:10200"
    restart: unless-stopped

  wyoming-satellite:
    container_name: wyoming-satellite
    image: sker65/wyoming-satellite:latest
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ./chatty-ww:/wake-word-models
    command: >
      --mic-command "arecord -D plughw:1,0 -f S16_LE -r 16000 -c 1"
      --snd-command "paplay --device=bluez_output.DA_1F_35_B9_D8_F5.1 -n Chatty"
      --uri tcp://0.0.0.0:10700
      --wake-word-name chatty
      --wake-command /wake-word-models/chatty.ppn
    ports:
      - "10700:10700"
    restart: unless-stopped