services:

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./home-assistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
    network_mode: host

  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model base.en
    ports:
      - "10300:10300"
    restart: unless-stopped

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice en_US-amy-low
    ports:
      - "10200:10200"
    restart: unless-stopped

  satellite:
    container_name: wyoming-satellite
    image: sker65/wyoming-satellite:latest
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./chatty-ww:/wake-word-models
    environment:
      - STT_HOST=localhost
      - STT_PORT=10300
      - TTS_HOST=localhost
      - TTS_PORT=10200
      - WAKE_WORD_ENABLED=true
      - WAKE_WORD_ENGINE=porcupine
      - WAKE_WORD_MODEL=/wake-word-models/chatty.ppn
      - WAKE_WORD_SENSITIVITY=0.6
    command: >
      --mic-command 'arecord -D plughw:2,0 -f S16_LE -r 16000 -c 1' 
      --speaker-command 'paplay --device=bluez_output.DA_1F_35_B9_D8_F5.1 -n Chatty'